CREATE DATABASE AUTOMATIZACAO;

USE AUTOMATIZACAO
GO

CREATE SCHEMA automatizacao

CREATE TABLE automatizacao.TIPO_ENVIO_WPP (
	ID_TIPO_ENVIO BIGINT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO_TIPO_ENVIO NVARCHAR(250)
)

INSERT INTO automatizacao.TIPO_ENVIO_WPP (DESCRICAO_TIPO_ENVIO)
VALUES ('MENSAGEM')

INSERT INTO automatizacao.TIPO_ENVIO_WPP (DESCRICAO_TIPO_ENVIO)
VALUES ('DOCUMENTO')

INSERT INTO automatizacao.TIPO_ENVIO_WPP (DESCRICAO_TIPO_ENVIO)
VALUES ('IMAGEM')

--SELECT * FROM automatizacao.TIPO_ENVIO_WPP

CREATE TABLE automatizacao.MENSAGEM_WPP (
	ID_MENSAGEM BIGINT IDENTITY(0,1) PRIMARY KEY,
	DESCRICAO_MENSAGEM NVARCHAR(4000)
)

INSERT INTO automatizacao.MENSAGEM_WPP (DESCRICAO_MENSAGEM)
VALUES (NULL)


INSERT INTO automatizacao.MENSAGEM_WPP (DESCRICAO_MENSAGEM)
VALUES ('Olá, tudo bem? Esse é um teste do robo que envia mensagem para os contatos do WhatsApp')

--SELECT * FROM automatizacao.MENSAGEM_WPP

CREATE TABLE automatizacao.CONTATOS_WPP (
	ID_CONTATO BIGINT IDENTITY(1,1) PRIMARY KEY,
	NOME NVARCHAR(250),
	TELEFONE BIGINT,
	ATIVO INT
)

INSERT INTO automatizacao.CONTATOS_WPP (NOME, TELEFONE, ATIVO)
VALUES ('Nome do contato', 00000000000, 1)

INSERT INTO automatizacao.CONTATOS_WPP (NOME, TELEFONE, ATIVO)
VALUES ('Nome do contato2', 00000000000, 1)

--SELECT * FROM automatizacao.CONTATOS_WPP

CREATE TABLE automatizacao.CONTROLE_ENVIO_WPP (
	ID_CONTROLE_ENVIO BIGINT IDENTITY(1,1) PRIMARY KEY,
	ID_CONTATO BIGINT,
	ID_TIPO_ENVIO BIGINT,
	ID_MENSAGEM BIGINT,
	CAMINHO_ARQUIVO NVARCHAR(4000)
)

INSERT INTO automatizacao.CONTROLE_ENVIO_WPP (ID_CONTATO, ID_TIPO_ENVIO, ID_MENSAGEM, CAMINHO_ARQUIVO)
VALUES (1, 1, 1, NULL)

INSERT INTO automatizacao.CONTROLE_ENVIO_WPP (ID_CONTATO, ID_TIPO_ENVIO, ID_MENSAGEM, CAMINHO_ARQUIVO)
VALUES (2, 2, 0, 'C:\testeSend\J. K. Rowling - Harry Potter 1 - Sorcerers Stone.txt')

INSERT INTO automatizacao.CONTROLE_ENVIO_WPP (ID_CONTATO, ID_TIPO_ENVIO, ID_MENSAGEM, CAMINHO_ARQUIVO)
VALUES (2, 2, 0, 'C:\testeSend\Teste RPA.docx')

INSERT INTO automatizacao.CONTROLE_ENVIO_WPP (ID_CONTATO, ID_TIPO_ENVIO, ID_MENSAGEM, CAMINHO_ARQUIVO)
VALUES (2, 2, 0, 'C:\testeSend\Teste RPA.pdf')

INSERT INTO automatizacao.CONTROLE_ENVIO_WPP (ID_CONTATO, ID_TIPO_ENVIO, ID_MENSAGEM, CAMINHO_ARQUIVO)
VALUES (1, 3, 1, 'C:\testeSend\harrypotter_2.jpeg')

--SELECT * FROM automatizacao.CONTROLE_ENVIO_WPP

SELECT C.*, A.ID_TIPO_ENVIO, B.DESCRICAO_TIPO_ENVIO, A.ID_MENSAGEM, A.CAMINHO_ARQUIVO, D.DESCRICAO_MENSAGEM
--SELECT *
FROM automatizacao.CONTROLE_ENVIO_WPP A
JOIN automatizacao.TIPO_ENVIO_WPP B ON A.ID_TIPO_ENVIO = B.ID_TIPO_ENVIO
JOIN automatizacao.CONTATOS_WPP C ON A.ID_CONTATO = C.ID_CONTATO
JOIN automatizacao.MENSAGEM_WPP D ON A.ID_MENSAGEM = D.ID_MENSAGEM
WHERE C.ATIVO = 1